### ISSUE TITLE
DockerHelper - Prüfung Docker-Installation in Install-NavDockerImage

### ISSUE THREAD

**Issue by varysswe** [varys-main/ps-tools#19]
# User Story

- Vor dem Download eines Images soll geprüft werden, ob Docker installiert ist. Sonst soll ein Hinweis mit Link zu Docker für Windows ausgegeben werden.

# Tasks

- [x] Auslagerung der Prüfung in eigene Funktion
- [x] Fehlermeldungen um Links erweitern (wo möglich)
- [x] Einbau in Install-NavDockerImage
- [x] Umstellung Add-NavDockerContainer

# Implementations

- Die Docker-Prüfungen wurden in die Funktion CheckDockerEnvironment ausgelagert.
- Die Funktion wird in allen Funktionen, die Docker benötigen, aufgerufen.

# Known Issues
