### ISSUE TITLE
Docker - Add-NavDockerContainer - includeCSide

### ISSUE THREAD

**Issue by varysswe** [varys-main/ps-tools#5]
# User Story

- In der Funktion Add-NavDockerContainer soll es möglich sein festzulegen, ob CSide für den neuen Container aktiviert werden soll.

# Tasks

- [x] Abfrage, ob CSide aktiviert werden soll
- [x] SWITCH-Parameter in interne NEW-Funktion
- [x] Übergabe an navcontainerhelper

# Implementations

- Es erfolgt ein Abfrage, ob CSide aktiviert werden soll

# Known Problems
