### ISSUE TITLE
DockerHelper - In Add-NavDockerContainer SQL-Benutzer aus DB löschen

### ISSUE THREAD

**Issue by varysswe** [varys-main/ps-tools#8]
# User Story

- Bei der Erstellung eines Containers mit einer vorhandenen DB können vorhandene NAV-Benutzer Probleme verursachen. Diese Benutzer sollen auf Rückfrage gelöscht werden.

# Tasks

- [x] Prüfung SQL-Aufrufe in PS
- [x] ~~Abfrage Nutzer löschen bei Verwendung eigener DB~~
- [x] ~~Benutzer mit SQL löschen~~
```sql 
delete
from
[dbo].[User]
delete
from
[dbo].[Access Control]
delete
from
[dbo].[User Property]
delete
from
[dbo].[Page Data Personalization]
delete from
[dbo].[User Default Style Sheet]
delete from
[dbo].[User Metadata]
delete from
[dbo].[User Personalization]
```

# Implementations

- Die Ausführung mit SQL ist zu unsicher, da die Tabellen sich innerhalb der Versionen ändern.
- Das Löschen per PowerShell scheitert, weil alle Benutzer noch angemeldet sind (warum auch immer).

# Known Problems

- Keine Umsetzung

**Comment by varysswe** [comment]
Keine Umsetzung
